problem 1:"select name from students"
problem 2:"select * from students where age>30"
problem 3:"select name from students where gender='F' and age=30"
problem 4:"select Points from students where name='Alex'"
problem 5:"insert into students(name,age,gender,points) values('Rami','24','M','450')"
problem 6:"update students set points=400 where name='Basma'"
problem 7:"update students set points=100 where name='Alex'"
